site_name: xNTTP Documentation
site_description: Documentation for the xNTTP landscape model for non-target terrestrial plants
repo_url: https://github.com/xlandscape/xNTTP
repo_name: xNTTP on GitHub
use_directory_urls: false

plugins:
  - search

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/sprout
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Introduction: introduction.md
  - xNTTP Overview:
      - Overview: xnttp/index.md
      - Components: xnttp/components.md
  - IBCgrass:
      - Intro: ibcgrass/index.md
      - Parameterisation: ibcgrass/parameterisation.md
      - PFT Preparation: ibcgrass/pft-preparation.md
      - Executable Inputs: ibcgrass/executable-inputs.md
  - Glossary: glossary.md